Add SLO test
ydb-platform/ydb-php-sdk pull request #105
Opened 2023-08-15 10:08 UTC by ilyakharev

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2023-08-16 08:46 UTC, ImpressionableRaccoon requested changes

2023-08-16 08:46 UTC, ImpressionableRaccoon commented on slo-workload/go-server/main.go
panic() можно в main, но тут у тебя вложенная другая функция

лучше возвращать пользователю какой-код через [http.Error](https://pkg.go.dev/net/http#Error)

2023-08-16 08:46 UTC, ImpressionableRaccoon commented on slo-workload/go-server/main.go
> +	log.Fatal(s.ListenAndServe())
вот тут как раз лучше panic(), потому что он выполняет все defer (которых пока нет)
log.Fatal() делает sys.exit()

2023-08-16 08:46 UTC, ImpressionableRaccoon commented on slo-workload/go-server/main.go
> +	"YDB_SESSION_BUSY"}
может на следующую строку скобку )

2023-08-16 08:46 UTC, ImpressionableRaccoon commented on slo-workload/go-server/main.go
> +	http.HandleFunc("/prepare", func(writer http.ResponseWriter, request *http.Request) {
Функции хендлеров лучше вынести отдельно, чтобы main не перегружать

2023-08-16 08:46 UTC, ImpressionableRaccoon commented on slo-workload/go-server/.golangci.yml
> +    #   - gofumpt
gofumpt хотелось бы видеть
и поправить module-path в конфиге выше

сейчас он может и бесполезный, но проект когда-нибудь разрастется на несколько пакетов

2023-08-22 07:52 UTC, ilyakharev commented
Moved to #106

2023-08-22 07:52 UTC, closed without merging